### ISSUE TITLE
Epic #1 Dinosaur Display

### ISSUE THREAD

**Issue by emerson-bualat** [chingu-voyages/v48-tier1-team-01#14]
**__Feature Description__**
- Display dinosaurs' names and corresponding images sourced from the provided JSON file.
- Each dinosaur entry should be clickable to view full details.

**__Major User Stories/tasks__**
- [x] User Story or Task  #1
- [x] User Story or Task #2
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.

**Comment by psmacabulos** [comment]
Dinosaur List for styling.
