### ISSUE TITLE
Epic #5 Responsiveness

### ISSUE THREAD

**Issue by emerson-bualat** [chingu-voyages/v48-tier1-team-01#18]
**__Feature Description__**

-  Ensure the web application is responsive and accessible across various devices and screen sizes.
-  Utilize responsive design techniques to adapt to different viewport sizes.

**__Major User Stories/tasks__**
- [ ] User Story or Task  #1
- [ ] User Story or Task #2
- [x] Make the Nav and Footer available for all screen sizes
- [ ] Additional User Stories or Tasks as necessary

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
